### ISSUE TITLE
npm ERR! natours@1.0.0 compile:sass: `node-sass sass/main.scss css/style.css`

### ISSUE THREAD

**Issue by mickeydp** [jonasschmedtmann/advanced-css-course#17]
> natours@1.0.0 compile:sass C:\Users\MICKEYDP\Desktop\natours
> node-sass sass/main.scss css/style.css

{
  "status": 1,
  "file": "C:/Users/MICKEYDP/Desktop/natours/sass/main.scss",
  "line": 30,
  "column": 7,
  "message": "Function rgb is missing argument $blue.",
  "formatted": "Error: Function rgb is missing argument $blue.\n        on line 30 of sass/main.scss\n>>       rgb($color-primary-light, 0.8),\r\n   ------^\n"
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! natours@1.0.0 compile:sass: `node-sass sass/main.scss css/style.css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the natours@1.0.0 compile:sass script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MICKEYDP\AppData\Roaming\npm-cache\_logs\2018-10-20T14_01_32_138Z-debug.log

**Comment by Aline09** [comment]
Hi Mike,
Maybe I can help you :)
You shoud try RGBA instead of rgb

**Comment by zakabdi** [comment]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! natours@1.0.0 compile:sass: `node-sass sass/main.scss css/style.css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the natours@1.0.0 compile:sass script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zakar\AppData\Roaming\npm-cache\_logs\2020-12-10T23_21_31_286Z-debug.log
PS C:\Users\zakar\OneDrive\Desktop\udemy design\natours>

**Comment by zakabdi** [comment]
this is not working when you runit , it would say " Failed at the natours@1.0.0 compile:sass script."
how do i fix this

**Comment by zulqarnainalisystemsltd** [comment]
Please use dart-sass instead of node-sass
But keep in minde that
dart-sass has been deprecated in favor of sass

According to sass, node-sass doesn't support color level 4. Therefore, I used the dart-sass compiler instead.
