### ISSUE TITLE
Natours avigation link appears (invisible, but clickable) over the other elements

### ISSUE THREAD

**Issue by leonimurilo** [jonasschmedtmann/advanced-css-course#2]
![screen shot 2018-01-01 at 15 37 20](https://user-images.githubusercontent.com/14261943/34469598-fc372524-ef09-11e7-8c66-ae633e5cba30.png)
As you can see, the nav bar links are overlapping the other elements even with the navigation bar not enabled and they are clickable making the interation with other elements impossible if they are under the links.

I tested the published version of the Natours page available at https://natours.netlify.com/ using google chrome on macOS.

Since I haven't reached the part of the course that the navbar was developed, I won't be able to find the most elegant solution for that.

**Comment by jonasschmedtmann** [comment]
Yes, this is an issue. The solution is to add `visibility: hidden`, as discussed in this post: [](https://www.udemy.com/advanced-css-and-sass/learn/v4/questions/3303484)

I'm not updating the code in the repo though, because I want it to be the exact same as in the course videos.

**Comment by AayushBangroo** [comment]
There's an issue with the navbar. When we first load the webpage or refresh the webpage we can clearly see the navbar items getting squished on the left side.How can we hide this?

**Comment by jonasschmedtmann** [comment]
Hi Aayush,

Please post this question in the official course Q&A on Udemy, this is the central place for all questions, and makes this information available to all students of the course :)

--
Jonas Schmedtmann
jonas.io<http://jonas.io> / @jonasschmedtman<https://twitter.com/jonasschmedtman>

On July 20, 2020 at 9:34 AM, AayushBangroo (notifications@github.com<mailto:notifications@github.com>) wrote:
There's an issue with the navbar. When we first load the webpage or refresh the webpage we can clearly see the navbar items getting squished on the left side.How can we hide this?
