### ISSUE TITLE
calc function doesn't works properly

### ISSUE THREAD

**Issue by avi3333** [jonasschmedtmann/advanced-css-course#22]
Hi,
I have come across a problem. I am now on natours sass section. I can't set the width of the columns with calc function. It shows error in chrome dev tool.
![capture](https://user-images.githubusercontent.com/40758004/47700715-a68c5600-dc41-11e8-8c05-9991d302e126.PNG)
![capture3](https://user-images.githubusercontent.com/40758004/47700716-a724ec80-dc41-11e8-8927-2e308f3f18f1.PNG)

Please help me.

**Comment by jonasschmedtmann** [comment]
Not really an issue. You just misspelled `calc`, you wrote `clac` instead.
Please use the course Q&A for this kind of problems in the future.
