### ISSUE TITLE
Mising coma

### ISSUE THREAD

**Issue by ReepNaj** [jonasschmedtmann/advanced-css-course#26]
Hi Jonas!

I hope your are doing great. First of all I want to thank you for your well designed course. So far I have learned a ton of awesome new stuff and I am looking forward to continue.

Like a lot of other people I ran into the same issue using the --watch flag. 
After watching your video again and paying more attention it works like a charm! VSC is such a great editor. I love the build in terminal function! Comes in really handy.

But anyway, I would like to make a comment on your 2nd solution. When using the two lines of code you provided  the terminal throws an error. When the two lines are separated by a coma everything is compiled well. 

Best,
Jan

**Comment by jonasschmedtmann** [comment]
Thanks for letting me know, will update in a future update :)
