### ISSUE TITLE
In Natours project, Rem is not working as expected

### ISSUE THREAD

**Issue by bharathvaj1995** [jonasschmedtmann/advanced-css-course#3]
![image](https://user-images.githubusercontent.com/16360498/34639618-48a21312-f309-11e7-93e1-a73ae6beb7cc.png)

Here you can see **body** paddind still remains 30px i mean it is not responsive. and the center text is larger the body.

**Comment by vapurrmaid** [comment]
@bharathvaj1995 is this from **section 2** ?
It should be fixed in **section 6** - "Advanced Responsive Design"

**Comment by bharathvaj1995** [comment]
Yes from (Even in Section 3) But in the tutorial video for @jonasschmedtmann it is working fine

**Comment by jonasschmedtmann** [comment]
This is not an issue at all, please just wait until we write the media queries in Section 6. How would the page be responsive without any media queries whatsoever?
