### ISSUE TITLE
mouse status display wrong on empty space

### ISSUE THREAD

**Issue by PhiNguyen1991** [jonasschmedtmann/advanced-css-course#7]
[http://prntscr.com/jd0wxf](url)

**Comment by jonasschmedtmann** [comment]
@PhiNguyen1991 this page doesn't lead anywhere, so I can't see the problem. Can you also post this to the course Q&A please?

**Comment by PhiNguyen1991** [comment]
can u send me the link ?

**Comment by jonasschmedtmann** [comment]
Sure: https://www.udemy.com/advanced-css-and-sass/learn/v4/questions
