### ISSUE TITLE
Downloaded ZIP file cannot extract

### ISSUE THREAD

**Issue by RavinduDharmasena** [jonasschmedtmann/advanced-css-course#70]
I have downloaded the project files from the GitHub to the computer as a ZIP file. But it says that the file is corrupted.

![Screenshot 2021-03-14 154505](https://user-images.githubusercontent.com/30996280/111064829-5180d000-84dc-11eb-8492-f840a391ced8.png)

**Comment by mosi3883** [comment]
maybe your download is corrupted, so try again and try other apps to unzip

**Comment by RavinduDharmasena** [comment]
Absolutely @mosi3883. I raise this as a issue after attempting 2 times to download from 2 stable internet connections. But as you mentioned in the reply, I downloaded it again and it is 100% OK. Damn internet connection !!! :-(
